# Generated by Django 2.0.13 on 2019-04-04 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.CharField(max_length=500)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('height', models.PositiveIntegerField(help_text='Please input in CM', validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('votes', models.PositiveIntegerField()),
            ],
        ),
    ]
