# Generated by Django 2.0.13 on 2019-04-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdolDetails',
            new_name='IdolDetail',
        ),
    ]
