# Generated by Django 2.0.13 on 2019-04-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0004_auto_20190404_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoldetail',
            name='namefirst',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='idoldetail',
            name='namelast',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='idoldetail',
            name='namemiddle',
            field=models.CharField(max_length=100),
        ),
    ]
