# Generated by Django 2.0.13 on 2019-04-04 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0005_auto_20190404_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoldetail',
            name='height',
            field=models.PositiveIntegerField(help_text='Please input in CM', validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='idoldetail',
            name='namemiddle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idoldetail',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
