# Generated by Django 2.0.13 on 2019-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0006_auto_20190404_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idoldetail',
            name='age',
        ),
        migrations.AlterField(
            model_name='idoldetail',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
