# Generated by Django 2.0.13 on 2019-04-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0010_auto_20190405_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdolSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idolsinger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise3app.IdolDetail')),
            ],
        ),
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
