# Generated by Django 2.0.13 on 2019-04-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise3app', '0012_auto_20190408_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdolSongs',
            new_name='IdolSongsPosition',
        ),
    ]
